# fly.toml app configuration file generated for glurve on 2025-08-12T21:13:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'glurve'
primary_region = 'lhr'

[build]
  dockerfile = '.nixpacks/Dockerfile'

[http_service]
  internal_port = 1234
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
